### ISSUE TITLE
MQTT -> "Unknown" Entities at HA. What's wrong?

### ISSUE THREAD

**Issue by HulkHoganNWO** [lukdwo/OpenWRT-collectd-MQTT-HA#6]
Hope you can help me,

maybe I did something wrong. Did it twice, but result is the same.
Did the instruction step-by-step. May there are a missunderstanding in it.

In Home-Assistant I have a few other MQTT-Devices and all working great. So this should not be the problem.
The MQTT-Data (IP, Port, Username, PW) are 100% ok. Have the same in all the other MQTT-Devices and as I sayed, they work well.

Hope you can see everything you need at the screenshots.
I check everything a few times and don't understand, why it's not gona work.

Did of course a few reboots with OpenWRT/Router and HA as well.

Thank you in advance.

![ha_configyaml](https://github.com/lukdwo/OpenWRT-collectd-MQTT-HA/assets/108953432/cc1b545d-eb7c-4aab-bda8-a1e83bb41862)
![ha_sensors](https://github.com/lukdwo/OpenWRT-collectd-MQTT-HA/assets/108953432/5c980ca1-a4a8-439a-90b6-367be29ad79e)
![mqtt conf](https://github.com/lukdwo/OpenWRT-collectd-MQTT-HA/assets/108953432/62698a56-a84d-45a6-8db5-63ae327de745)
![openwrtcollectd](https://github.com/lukdwo/OpenWRT-collectd-MQTT-HA/assets/108953432/ea3ee3cc-6bf0-4785-8084-a7d99626a77f)
![openwrtcollectd2](https://github.com/lukdwo/OpenWRT-collectd-MQTT-HA/assets/108953432/818de803-aff7-414c-9d9c-f11dfb5d0b22)
![openwrtinstalledcollectd](https://github.com/lukdwo/OpenWRT-collectd-MQTT-HA/assets/108953432/5d3a02c2-e28a-44ef-95d9-c2d9dc3d296c)
![openwrtinstalledluci](https://github.com/lukdwo/OpenWRT-collectd-MQTT-HA/assets/108953432/eebb93d6-1b1e-4f8c-a8ed-8e5e4ed58a67)
![openwrtsystem](https://github.com/lukdwo/OpenWRT-collectd-MQTT-HA/assets/108953432/c89b7e69-9265-45eb-8a9c-771ac39b8ed1)

**Comment by lukdwo** [comment]
It looks like past in vi editor which cut firs few letters. Make sure that first line is: LoadPlugin mqtt
Lessons learned - int the future use Ctrl+a to enable edit mode in vi and past after that.
If you still face this issue check: https://github.com/lukdwo/OpenWRT-collectd-MQTT-HA/issues/4#issuecomment-1866667143

**Comment by HulkHoganNWO** [comment]
Thank you, very much. Missed that faulty config by checking only the edited values.

After scrolling through https://github.com/lukdwo/OpenWRT-collectd-MQTT-HA/issues/4#issuecomment-1866667143 everything works!
Thanks mate.
